In [4]:
import os
os.getcwd()

'd:\\Bala\\Recruitment_Prediction\\notebook'

In [5]:
os.chdir("../")

In [24]:
from neuro_mf import ModelFactory

from recruitment.utils.main_utils import load_numpy_array_data

In [7]:
train =  load_numpy_array_data(r"artifact\07_13_2024_00_32_21\data_transformation\transformed\train.npy")
test = load_numpy_array_data(r"artifact\07_13_2024_00_32_21\data_transformation\transformed\test.npy")

In [8]:
train

array([[-1.21798536,  0.92104872,  1.4602557 , ..., -0.23092318,
         0.16378364,  1.        ],
       [-0.23880999, -0.15222615,  1.4602557 , ..., -1.3759968 ,
         0.16378364,  0.        ],
       [ 0.30517632,  1.13570369,  1.4602557 , ..., -0.23092318,
         0.16378364,  0.        ],
       ...,
       [-0.78279631, -1.01084605,  0.03561599, ..., -0.23092318,
         0.16378364,  0.        ],
       [ 0.9579599 ,  0.49173877, -1.38902372, ..., -0.23092318,
         0.16378364,  0.        ],
       [ 0.84916264,  1.35035866,  0.03561599, ..., -0.23092318,
        -1.28136611,  1.        ]])

In [9]:
test

array([[-1.1091881 , -0.15222615, -0.67670386, ...,  0.91415044,
         1.60893338,  1.        ],
       [ 1.06675717, -1.22550102,  0.74793585, ...,  2.05922405,
         0.16378364,  0.        ],
       [-1.00039084, -1.65481097,  0.74793585, ..., -0.23092318,
        -1.28136611,  1.        ],
       ...,
       [-1.32678263, -1.22550102,  1.4602557 , ..., -1.3759968 ,
         1.60893338,  0.        ],
       [ 0.52277085, -0.79619107, -0.67670386, ..., -0.23092318,
         1.60893338,  0.        ],
       [-1.54437715, -1.22550102, -1.38902372, ..., -0.23092318,
         0.16378364,  0.        ]])

In [10]:
model_config_filepath = r"config\model.yaml"

In [25]:
model_config_filepath = r"config\model.yaml"

model_factory = ModelFactory(model_config_path=model_config_filepath)

x_train, y_train, x_test, y_test = train[:, :-1], train[:, -1], test[:, :-1], test[:, -1]

best_model_detail = model_factory.get_best_model(X=x_train,y=y_train)

TypeError: 'NoneType' object is not subscriptable

In [11]:
from catboost import CatBoostClassifier

In [12]:
cb = CatBoostClassifier()

In [13]:
x_train, y_train, x_test, y_test = train[:, :-1], train[:, -1], test[:, :-1], test[:, -1]

In [15]:
x_train.shape

(1200, 10)

In [16]:
y_train.shape

(1200,)

In [17]:
x_test.shape

(300, 10)

In [18]:
y_test.shape

(300,)

In [19]:
cb.fit(x_train,y_train)


Learning rate set to 0.011136
0:	learn: 0.6827861	total: 147ms	remaining: 2m 26s
1:	learn: 0.6746898	total: 150ms	remaining: 1m 14s
2:	learn: 0.6613907	total: 152ms	remaining: 50.6s
3:	learn: 0.6536496	total: 155ms	remaining: 38.6s
4:	learn: 0.6427013	total: 158ms	remaining: 31.3s
5:	learn: 0.6324616	total: 160ms	remaining: 26.6s
6:	learn: 0.6242977	total: 163ms	remaining: 23.1s
7:	learn: 0.6155577	total: 166ms	remaining: 20.6s
8:	learn: 0.6039555	total: 168ms	remaining: 18.5s
9:	learn: 0.5978506	total: 171ms	remaining: 16.9s
10:	learn: 0.5918697	total: 174ms	remaining: 15.6s
11:	learn: 0.5818355	total: 176ms	remaining: 14.5s
12:	learn: 0.5715560	total: 179ms	remaining: 13.6s
13:	learn: 0.5651077	total: 181ms	remaining: 12.8s
14:	learn: 0.5568241	total: 184ms	remaining: 12.1s
15:	learn: 0.5491292	total: 187ms	remaining: 11.5s
16:	learn: 0.5449345	total: 188ms	remaining: 10.9s
17:	learn: 0.5377824	total: 191ms	remaining: 10.4s
18:	learn: 0.5312766	total: 194ms	remaining: 10s
19:	learn: 

In [22]:
y_pred = cb.predict(x_test)
y_pred

array([1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0.

In [23]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

confusion_matrix(y_test,y_pred)

array([[207,   5],
       [ 13,  75]], dtype=int64)

In [27]:
os.getcwd()

'd:\\Bala\\Recruitment_Prediction'

In [28]:
import pandas as pd

In [29]:
df1 = pd.read_csv("recruitment_data.csv")

In [30]:
df1.head()

Age  Gender  ...  RecruitmentStrategy  HiringDecision
0   26       1  ...                    1               1
1   39       1  ...                    2               1
2   48       0  ...                    2               0
3   34       1  ...                    3               0
4   30       0  ...                    2               0

[5 rows x 11 columns]

In [33]:
df1.iloc[:,:-1]

Age  Gender  ...  PersonalityScore  RecruitmentStrategy
0      26       1  ...                91                    1
1      39       1  ...                80                    2
2      48       0  ...                13                    2
3      34       1  ...                70                    3
4      30       0  ...                85                    2
...   ...     ...  ...               ...                  ...
1495   48       0  ...                80                    3
1496   27       1  ...                 7                    2
1497   24       1  ...                58                    1
1498   48       0  ...                44                    2
1499   34       1  ...                26                    2

[1500 rows x 10 columns]

In [34]:
X= df1.iloc[:,:-1]
y=df1.iloc[:,-1]

In [38]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

cb.fit(X_train,y_train)

y_pred = cb.predict(X_test)

confusion_matrix(y_test,y_pred)


Learning rate set to 0.011136
0:	learn: 0.6839150	total: 2.09ms	remaining: 2.09s
1:	learn: 0.6727741	total: 3.86ms	remaining: 1.93s
2:	learn: 0.6601190	total: 5.68ms	remaining: 1.89s
3:	learn: 0.6533644	total: 7.18ms	remaining: 1.79s
4:	learn: 0.6446967	total: 8.78ms	remaining: 1.75s
5:	learn: 0.6345500	total: 10.3ms	remaining: 1.71s
6:	learn: 0.6259566	total: 12ms	remaining: 1.7s
7:	learn: 0.6150375	total: 13.5ms	remaining: 1.67s
8:	learn: 0.6059274	total: 14.9ms	remaining: 1.64s
9:	learn: 0.5994476	total: 16.3ms	remaining: 1.62s
10:	learn: 0.5899305	total: 17.8ms	remaining: 1.6s
11:	learn: 0.5804608	total: 19.3ms	remaining: 1.59s
12:	learn: 0.5737372	total: 20.8ms	remaining: 1.58s
13:	learn: 0.5670148	total: 22.2ms	remaining: 1.56s
14:	learn: 0.5615577	total: 23.7ms	remaining: 1.55s
15:	learn: 0.5549535	total: 24.8ms	remaining: 1.53s
16:	learn: 0.5504299	total: 25.9ms	remaining: 1.5s
17:	learn: 0.5405803	total: 27.3ms	remaining: 1.49s
18:	learn: 0.5354439	total: 28.5ms	remaining: 1.4

array([[209,   6],
       [  8,  77]], dtype=int64)

In [39]:
from neuro_mf import ModelFactory

In [40]:
model_config_filepath

'config\\model.yaml'

In [49]:
model_config_filepath = r"config\model.yaml"

model_factory = ModelFactory(model_config_path=model_config_filepath)

#x_train, y_train, x_test, y_test = train[:, :-1], train[:, -1], test[:, :-1], test[:, -1]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

best_model_detail = model_factory.get_best_model(X=X_train,y=y_train)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
Learning rate set to 0.5
0:	learn: 0.5377889	total: 488us	remaining: 4.39ms
1:	learn: 0.4687613	total: 836us	remaining: 3.35ms
2:	learn: 0.4409786	total: 1.21ms	remaining: 2.82ms
3:	learn: 0.4045815	total: 1.49ms	remaining: 2.24ms
4:	learn: 0.3724121	total: 1.83ms	remaining: 1.83ms
5:	learn: 0.3567366	total: 2.17ms	remaining: 1.44ms
6:	learn: 0.3359120	total: 2.49ms	remaining: 1.07ms
7:	learn: 0.3236251	total: 2.81ms	remaining: 702us
8:	learn: 0.3128949	total: 3.15ms	remaining: 350us
9:	learn: 0.3048974	total: 3.48ms	remaining: 0us
[CV 1/3] END ............depth=2, iterations=10;, score=0.935 total time=   0.0s
Learning rate set to 0.5
0:	learn: 0.5313718	total: 405us	remaining: 3.65ms
1:	learn: 0.4749516	total: 701us	remaining: 2.8ms
2:	learn: 0.4367979	total: 985us	remaining: 2.3ms
3:	learn: 0.3956560	total: 1.26ms	remaining: 1.89ms
4:	learn: 0.3753777	total: 1.55ms	remaining: 1.55ms
5:	learn: 0.3610018	total: 1.84ms	remaini

In [42]:
best_model_detail

GridSearchedBestModel(model_serial_number='module_1', model=RandomForestClassifier(max_depth=10, n_estimators=3), best_model=RandomForestClassifier(max_depth=15, max_features='log2', n_estimators=9), best_parameters={'max_depth': 15, 'max_features': 'log2', 'n_estimators': 9}, best_score=0.8908333333333335)

In [48]:
cb = CatBoostClassifier(iterations=10,learning_rate=0.1,depth=6)
cb.fit(X_train,y_train)

0:	learn: 0.6541175	total: 1.48ms	remaining: 13.3ms
1:	learn: 0.6161672	total: 2.79ms	remaining: 11.2ms
2:	learn: 0.5856139	total: 3.9ms	remaining: 9.1ms
3:	learn: 0.5527100	total: 5.35ms	remaining: 8.02ms
4:	learn: 0.5192899	total: 6.63ms	remaining: 6.63ms
5:	learn: 0.4940391	total: 7.74ms	remaining: 5.16ms
6:	learn: 0.4722836	total: 8.97ms	remaining: 3.84ms
7:	learn: 0.4569149	total: 9.98ms	remaining: 2.5ms
8:	learn: 0.4374870	total: 10.9ms	remaining: 1.21ms
9:	learn: 0.4139868	total: 11.9ms	remaining: 0us


In [47]:
pred = cb.predict(X_test)
confusion_matrix(y_test,pred)

array([[188,  27],
       [ 21,  64]], dtype=int64)